# @doc https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  scrape_interval: 15s
  scrape_timeout: 10s
# @doc https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
scrape_configs:
  - job_name: 'bpf'
    static_configs:
      - targets: ['bpf-exporter:9435']
        labels:
          group: 'bpf-exporter'
