apiVersion: v1
kind: Service
metadata:
  name: api-app
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  strategy:
    type: "RollingUpdate"
  minReadySeconds: 0
  revisionHistoryLimit: 5
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        environment: dev
    spec:
      containers:
        - name: api-app
          image: api-app:test
          # use the local image
          # https://kubernetes.io/docs/concepts/containers/images/#:~:text=The%20default%20pull%20policy%20is,of%20the%20container%20to%20Always%20.&text=omit%20the%20imagePullPolicy%20and%20the%20tag%20for%20the%20image%20to%20use.
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
