apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  type: NodePort
  selector:
    component: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          # Use `-oss` version https://www.docker.elastic.co/#
          # without X-Pack feature https://discuss.elastic.co/t/how-to-use-docker-without-xpack-features-aka-how-to-make-the-license-expiration-message-go-away/147236/4
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
          env:
            # forms a single-node cluster and avoid discovering other nodes
            # https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-settings.html
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 1.5Gi
            # HACK: default request does not work locally because of OOM
            # requests:
            #   cpu: 500m
            #   memory: 4Gi
